version: "3.9"
services:
  mysql:
    container_name: db
    image: mysql:latest
    ports:
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: CMPT371-team1
    volumes:
    - ./mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pCMPT371-team1"]
      interval: 5s
      timeout: 3s
      retries: 3

  node:
    container_name: backend
    build: 
      context: ./back-end
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./back-end/src/resources/development.env
    ports: 
      - 3000:3000
    volumes: 
      - ./back-end:/usr/project/back-end
      - /usr/project/back-end/node_modules
    depends_on: 
      mysql:
        condition: service_healthy
  
  
