version: "3.9"
services:
  mysql:
    container_name: db
    image: mysql:5.7
    ports:
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: CMPT371-team1
    volumes:
    - ./mysql-volume:/var/lib/mysql

  tests_container:
    container_name: tests_container
    build: 
      context: ./back-end
      dockerfile: Dockerfile
      target: test
    ports: 
      - 3000:3000
    volumes: 
      - ./back-end:/usr/project/back-end
      - /usr/project/back-end/node_modules
    depends_on: 
      - mysql
    command: >
      sh -c "
        npm run system-tests &&
        npm run smoke-tests &&
        npm run unit-tests
      "

