version: "3.9"
services: 
  node:
    container_name: backend
    build: 
      context: ./back-end
      dockerfile: Dockerfile
      target: dev
    ports: 
      - 3000:3000
    volumes: 
      - ./back-end:/usr/project/back-end
      - /usr/project/back-end/node_modules
    depends_on: 
      - mysql
  
  mysql:
    container_name: db
    image: mysql:5.7
    ports:
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: CMPT371-team1
    volumes:
    - ./mysql-volume:/var/lib/mysql