version: '3.9'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./dbfiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: CMPT371-Team1
  node:
    build: .
    container_name: nodejs
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
        condition: service_started
    stdin_open: true
    tty: true