version: "3.9"
services: 
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql
  
  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: CMPT371-team1