name: cd

on:
  push:
    branches:
      - master

jobs:
  webhook-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
               -d '{"ref": "refs/heads/master", "before": "", "after": ""}' \
               https://casi-survey.usask.ca/webhook

