name: Continuous Deployment

on:
  push:
    branches:
      - cd-runner-config

jobs:
  execute-workflow-script:
    runs-on: cd-runner
    name: Execute workflow.sh on cd-runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Execute workflow script
      run: |
        /server/workflow.sh
