name: Continious Deployment

on:
  push:
    branches:
      - master

jobs:
  webhook-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
               -d '{"ref": "${{ github.ref }}", "before": "${{ github.before }}", "after": "${{ github.after }}"}' \
               $WEBHOOK_URL
