name: ci

on:
  pull_request:
    branches: [ development, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Enforce merge into master from dev only
      if: github.base_ref == 'master' && github.head_ref != 'development'
      run: |
        echo "ERROR: You can only merge to master from development"
        exit 1
        
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Test Container and Run Tests
      run: docker compose -f docker-compose.test.yml up --exit-code-from tests_container --attach tests_container