name: ci

on:
    workflow_dispatch:
#   push:
#     branches:
#       - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test backend
        uses: docker/build-push-action@v5
        with:
          context: ./back-end
          target: test
        #   load: true
      -
        name: Build and test frontend
        uses: docker/build-push-action@v5
        with:
            context: ./front-end
            target: test
        #   load: true