name: ci

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test backend
        uses: docker/build-push-action@v5
        with:
          context: ./back-end
          target: test
        #   load: true
      - name: Build and test frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          target: test
        #   load: true

      #name:  Run Smoke Tests
      #run: npm run smoke-test # command to run smoke tests at merge to master

      #name: Run System tests
      #run: npm run system-test command to run system tests at merge to master
